#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorC,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                   - Moving Forward then Backward-                                      *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your taskbot in a square five times.                                                *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  To change the forward movement speed replace the two "100"'s with the desired speed number.     *|
|*        (Negative numbers are the reverse equivalent.)                                                  *|
|*    2)  To change the duration of the movement, replace the "4000" with the desired number of           *|
|*        milliseconds.                                                                                   *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/
void forwardTime(int t, int percentPower);
void forwardRev (int rev, int percentPower);
task main()

{

	 //forwardTime(4000,20); // Move forward for 4 seconds.
	 //wait1Msec(5000);
	 //forwardTime(1000,-20);
	 //wait1Msec(2500);
   forwardTime(3000, 30);
	 motor[motorB] = 50;
	 motor[motorC] = 0;
	 motor[motorB] = 50;
	 motor[motorC] = 0;
	 wait1Msec(3500);
	 forwardTime(3000,20);

//	forwardRev(2, 80); //Move forward for 1,496 degrees.


}

void forwardTime(int t, int percentPower){
	motor[motorC] = percentPower;
	motor[motorB] = percentPower;

	wait1Msec(t);

	motor[motorC] = 0;
	motor[motorB] = 0;

}

void forwardRev (int rev,int percentPower) {

	nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorB] = 0;

	while	((nMotorEncoder[motorC] < rev) && (nMotorEncoder[motorB] < rev)){
		motor[motorC] = percentPower;
		motor[motorB] = percentPower;

	}
	nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorB] = 0;

	motor[motorC] = 0;
	motor[motorB] = 0;
}
